insert into person_tb(first_name, last_name, address, gender, enabled) values ('Barty', 'Philippe', '15th Floor', 'Male', false),
('Trevar', 'Greber', '11th Floor', 'Male', false),
('Dugald', 'Simmen', 'Room 1442', 'Male', true),
('Myriam', 'Drillot', '15th Floor', 'Female', false),
('Dominica', 'Putton', 'Apt 538', 'Female', false),
('Hermie', 'Harsant', 'Room 540', 'Male', false),
('Daron', 'Druitt', 'Apt 1755', 'Male', true),
('Rebeca', 'Cheng', '16th Floor', 'Female', true),
('Ransell', 'Lindfors', 'PO Box 72452', 'Male', true),
('Jyoti', 'Overnell', 'Room 159', 'Female', true),
('Wileen', 'Leemans', '3rd Floor', 'Female', false),
('Adolpho', 'Phayre', 'Suite 20', 'Male', true),
('Linea', 'Reynish', 'Room 658', 'Female', true),
('Friedrick', 'Kinmond', 'Room 540', 'Male', true),
('Jodee', 'Luppitt', '3rd Floor', 'Female', true),
('Marcy', 'Carne', 'Apt 1670', 'Female', false),
('Kurtis', 'Penhalurick', 'PO Box 96205', 'Male', false),
('Sterling', 'Oxterby', 'Apt 954', 'Male', false),
('Free', 'Dodamead', 'Room 1523', 'Male', false),
('Elwira', 'Ishaki', 'Suite 62', 'Female', false),
('Letta', 'Piletic', 'Room 1565', 'Female', false),
('Charlot', 'Stonebanks', '12th Floor', 'Female', false),
('Rudd', 'Cicullo', 'Room 1223', 'Male', false),
('Sal', 'Gurnell', '6th Floor', 'Male', false),
('Leodora', 'McCaster', 'Apt 1292', 'Female', true),
('Carine', 'Reddecliffe', 'Apt 1732', 'Female', true),
('Stanford', 'Stothard', 'PO Box 58936', 'Male', false),
('Emelina', 'Cutbush', 'Suite 18', 'Female', true),
('Lanette', 'Spykings', 'Room 1700', 'Female', true),
('Elvyn', 'Anfossi', '7th Floor', 'Male', false),
('Caprice', 'Lettsom', 'PO Box 68139', 'Female', false),
('Derry', 'Preene', 'Apt 1397', 'Male', false),
('Claudius', 'Hulstrom', 'Apt 782', 'Male', false),
('Gaylene', 'Hein', 'Apt 346', 'Female', true),
('Linus', 'Zanettini', 'Room 1411', 'Male', false),
('Darbee', 'Dransfield', 'Room 1120', 'Male', true),
('Allard', 'Gowthorpe', 'PO Box 16324', 'Male', false),
('Daisie', 'Critchell', 'Apt 1260', 'Female', true),
('Neron', 'Hendin', 'Room 1362', 'Male', true),
('Anne-corinne', 'O''Gleasane', 'Suite 73', 'Female', true),
('Eachelle', 'Leason', '19th Floor', 'Female', true),
('Camile', 'Gyngell', 'PO Box 51318', 'Female', false),
('Yul', 'Kitter', 'PO Box 16035', 'Male', false),
('Henryetta', 'Grellier', 'Apt 1265', 'Female', true),
('Shirl', 'McKague', '12th Floor', 'Female', false),
('Leo', 'Summerton', 'PO Box 71147', 'Male', true),
('Aubine', 'Gyngyll', '16th Floor', 'Female', false),
('Ashli', 'Reinbech', 'PO Box 90325', 'Female', false),
('Cassondra', 'Salvin', 'Apt 1198', 'Female', false),
('Vivianna', 'Whitham', 'Room 591', 'Female', true),
('Itch', 'Cossam', 'Room 1851', 'Male', false),
('Blondie', 'Kundert', 'PO Box 47992', 'Female', true),
('Marc', 'Boughton', '18th Floor', 'Male', true),
('Ware', 'McKinnon', '3rd Floor', 'Male', false),
('Bili', 'Vynall', 'Apt 1050', 'Female', true),
('Mannie', 'Kincaid', 'Suite 82', 'Male', true),
('Zilvia', 'Rambadt', 'Apt 1978', 'Female', false),
('Hilliary', 'Windridge', 'Room 777', 'Female', false),
('Ulises', 'Dubock', 'PO Box 56081', 'Male', false),
('Mateo', 'Gniewosz', '18th Floor', 'Male', true),
('Marje', 'Longstreet', 'Suite 49', 'Female', false),
('Gibby', 'Nasey', 'Apt 1755', 'Male', true),
('Rhonda', 'Meddings', '2nd Floor', 'Female', false),
('Nappie', 'Galego', 'Apt 1641', 'Male', false),
('Hartley', 'Delacourt', '12th Floor', 'Male', false),
('Doll', 'Denny', 'Suite 67', 'Female', false),
('Sean', 'Plomer', 'PO Box 87328', 'Female', true),
('Carlene', 'Franek', 'Suite 18', 'Female', false),
('Trina', 'Bottoms', '9th Floor', 'Female', true),
('Kelsy', 'Lismore', 'Suite 9', 'Female', true),
('Heda', 'Benninger', 'Apt 1514', 'Female', true),
('Jobi', 'Mardy', 'PO Box 68525', 'Female', false),
('Tremaine', 'Farington', '18th Floor', 'Male', true),
('Rob', 'Jacob', 'Room 420', 'Male', true),
('Birgitta', 'Allison', 'PO Box 65486', 'Female', true),
('Boy', 'McOrkill', '17th Floor', 'Male', false),
('Queenie', 'Fuzzey', 'Suite 66', 'Female', true),
('Pammy', 'Scoon', '7th Floor', 'Female', false),
('Kermie', 'Preedy', '1st Floor', 'Male', true),
('Verne', 'Piscotti', '18th Floor', 'Male', true),
('Skelly', 'Mushrow', 'PO Box 85013', 'Male', false),
('Maynard', 'Benko', 'Suite 25', 'Male', true),
('Gardie', 'Brierley', 'Room 1664', 'Male', true),
('Dori', 'Oldford', 'PO Box 10916', 'Female', false),
('Arda', 'Donaho', 'Apt 1149', 'Female', true),
('Cherice', 'Winsor', '20th Floor', 'Female', true),
('Hartley', 'Plows', 'Suite 27', 'Male', false),
('Donnell', 'Cruise', 'Apt 587', 'Male', false),
('Traci', 'Portam', 'Room 709', 'Female', false),
('Dieter', 'Tocknell', 'PO Box 68354', 'Male', true),
('Maybelle', 'Elsmor', 'Room 66', 'Female', false),
('Matthiew', 'Albrook', 'Suite 91', 'Male', true),
('Debor', 'Sheffield', 'Apt 422', 'Female', false),
('Quill', 'Toten', 'PO Box 98503', 'Male', false),
('Jany', 'Edgson', 'Room 1371', 'Female', true),
('Jemie', 'Maciaszczyk', '9th Floor', 'Female', true),
('Nathanial', 'Boodle', 'Apt 1587', 'Male', true),
('Wolf', 'Shergill', '14th Floor', 'Male', true),
('Winona', 'Espinay', 'Suite 20', 'Female', true),
('Burt', 'Huerta', 'Apt 1757', 'Male', true);